n = input('Введите последовательность ДНК: ').upper()
A = n.count('A')
T = n.count('T')
G = n.count('G')
C = n.count('C')
l = len(n)
print('Подсчёт нуклеотидов: ')
print(f'{A} аденинов')
print(f'{T} тиминов')
print(f'{G} гуанинов')
print(f'{C} цитозинов')
print(f'Общая длина: {l} нуклеотидов')