services:

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
    volumes:
      - ./pgdata_testdb:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes: {}