print('===  Анализ последовательности ДНК  ===')
dna = input('Введите последовательность ДНК: ')
#c is correct
dna_c = dna.upper()
print(f'Последовательность в верхнем регистре: {dna_c}\nПодсчёт нуклеотидов:')
a = dna_c.count('A')
t = dna_c.count('T')
g = dna_c.count('G')
c = dna_c.count('C')
print(f'A: {a}\nT: {t}\nG: {g}\nC: {c}')
l = len(dna)
print(f'Общая длина: {l} нуклеотидов')